name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 실행
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run tests
        run: |
          pytest
      
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Create deployment package
        run: |
          mkdir -p deployment-package
          cp -r dispatch deployment-package/
          cp qna_flows_rest_api.py deployment-package/
          cd deployment-package
          pip install -r ../requirements.txt -t .
          zip -r ../deployment-package.zip .
      
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://deployment-package.zip
      
      - name: Update Lambda environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --environment "Variables={BEDROCK_FLOW_ID=${{ secrets.BEDROCK_FLOW_ID }}}"